// react-app/src/components/UserManager.jsx
import { useState, useEffect } from "react";
import "./UserManager.css";

const API_URL = "http://localhost:3001";

function UserManager() {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    role: "",
  });
  const [editingId, setEditingId] = useState(null);

  // GET - Fetch all users
  const fetchUsers = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${API_URL}/users`);
      if (!response.ok) throw new Error("Failed to fetch users");
      const data = await response.json();
      setUsers(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  // POST - Create new user
  const createUser = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${API_URL}/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });
      if (!response.ok) throw new Error("Failed to create user");
      await fetchUsers();
      setFormData({ name: "", email: "", role: "" });
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // PUT - Update user
  const updateUser = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${API_URL}/users/${editingId}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ ...formData, id: editingId }),
      });
      if (!response.ok) throw new Error("Failed to update user");
      await fetchUsers();
      setFormData({ name: "", email: "", role: "" });
      setEditingId(null);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // DELETE - Delete user
  const deleteUser = async (id) => {
    if (!window.confirm("Are you sure you want to delete this user?")) return;

    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${API_URL}/users/${id}`, {
        method: "DELETE",
      });
      if (!response.ok) throw new Error("Failed to delete user");
      await fetchUsers();
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const startEdit = (user) => {
    setEditingId(user.id);
    setFormData({
      name: user.name,
      email: user.email,
      role: user.role,
    });
  };

  const cancelEdit = () => {
    setEditingId(null);
    setFormData({ name: "", email: "", role: "" });
  };

  const handleSubmit = editingId ? updateUser : createUser;

  return (
    <div className="user-manager">
      <h2>👥 User Management (CRUD Operations)</h2>

      {error && (
        <div className="error" data-testid="error-message">
          Error: {error}
        </div>
      )}

      <form
        onSubmit={handleSubmit}
        className="user-form"
        data-testid="user-form"
      >
        <h3>{editingId ? "Edit User" : "Add New User"}</h3>
        <input
          type="text"
          placeholder="Name"
          value={formData.name}
          onChange={(e) => setFormData({ ...formData, name: e.target.value })}
          required
          data-testid="input-name"
        />
        <input
          type="email"
          placeholder="Email"
          value={formData.email}
          onChange={(e) => setFormData({ ...formData, email: e.target.value })}
          required
          data-testid="input-email"
        />
        <input
          type="text"
          placeholder="Role"
          value={formData.role}
          onChange={(e) => setFormData({ ...formData, role: e.target.value })}
          required
          data-testid="input-role"
        />
        <div className="form-actions">
          <button type="submit" disabled={loading} data-testid="submit-button">
            {loading ? "Processing..." : editingId ? "Update User" : "Add User"}
          </button>
          {editingId && (
            <button
              type="button"
              onClick={cancelEdit}
              data-testid="cancel-button"
            >
              Cancel
            </button>
          )}
        </div>
      </form>

      <div className="users-list">
        <h3>Users List</h3>
        {loading && <p>Loading...</p>}
        {users.length === 0 && !loading && <p>No users found</p>}
        <div className="users-grid" data-testid="users-list">
          {users.map((user) => (
            <div
              key={user.id}
              className="user-card"
              data-testid={`user-${user.id}`}
            >
              <h4>{user.name}</h4>
              <p>📧 {user.email}</p>
              <p>💼 {user.role}</p>
              <div className="card-actions">
                <button
                  onClick={() => startEdit(user)}
                  className="btn-edit"
                  data-testid={`edit-user-${user.id}`}
                >
                  ✏️ Edit
                </button>
                <button
                  onClick={() => deleteUser(user.id)}
                  className="btn-delete"
                  data-testid={`delete-user-${user.id}`}
                >
                  🗑️ Delete
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default UserManager;

// angular-app/src/app/components/user-manager/user-manager.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { UserService, User } from '../../services/user';

@Component({
  selector: 'app-user-manager',
  imports: [CommonModule, FormsModule],
  templateUrl: './user-manager.html',
  styleUrl: './user-manager.css',
})
export class UserManager implements OnInit {
  users: User[] = [];
  loading = false;
  error: string | null = null;
  formData: User = {
    name: '',
    email: '',
    role: '',
  };
  editingId: number | null = null;

  constructor(private userService: UserService) {}

  ngOnInit(): void {
    this.fetchUsers();
  }

  // GET - Fetch all users
  fetchUsers(): void {
    this.loading = true;
    this.error = null;
    this.userService.getUsers().subscribe({
      next: (data) => {
        this.users = data;
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message;
        this.loading = false;
      },
    });
  }

  // POST - Create new user
  createUser(): void {
    this.loading = true;
    this.error = null;
    this.userService.createUser(this.formData).subscribe({
      next: () => {
        this.fetchUsers();
        this.resetForm();
      },
      error: (err) => {
        this.error = err.message;
        this.loading = false;
      },
    });
  }

  // PUT - Update user
  updateUser(): void {
    if (this.editingId === null) return;

    this.loading = true;
    this.error = null;
    this.userService
      .updateUser(this.editingId, { ...this.formData, id: this.editingId })
      .subscribe({
        next: () => {
          this.fetchUsers();
          this.resetForm();
          this.editingId = null;
        },
        error: (err) => {
          this.error = err.message;
          this.loading = false;
        },
      });
  }

  // DELETE - Delete user
  deleteUser(id: number): void {
    if (!confirm('Are you sure you want to delete this user?')) return;

    this.loading = true;
    this.error = null;
    this.userService.deleteUser(id).subscribe({
      next: () => {
        this.fetchUsers();
      },
      error: (err) => {
        this.error = err.message;
        this.loading = false;
      },
    });
  }

  startEdit(user: User): void {
    this.editingId = user.id!;
    this.formData = {
      name: user.name,
      email: user.email,
      role: user.role,
    };
  }

  cancelEdit(): void {
    this.editingId = null;
    this.resetForm();
  }

  resetForm(): void {
    this.formData = {
      name: '',
      email: '',
      role: '',
    };
  }

  onSubmit(): void {
    if (this.editingId) {
      this.updateUser();
    } else {
      this.createUser();
    }
  }
}
